# Generated by Django 2.1.7 on 2019-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroffer',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caroffer',
            name='otomoto_id',
            field=models.CharField(default=0, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
